@startuml csbq

class SlenderBodyElem {
    - cheb_order
    - fourier_order
    - comm
    - radius
    - coord
    - elem_dsp

    constructor()
    destructor()
    sctl::Vector CenterlineNodes()
    sctl::Long Size()
    void GetNodeCoord()
    void Write()
    void Read()
    void WriteVTK()

}

class BoundaryIntegralOp {
    constructor()
    destructor()
    void SetAccuracy()
    void AddElemList()
    void SetTargetCoord()
    void SetTargetNormal()

    void ComputePotential()
}

class GMRES {
    constructor()
    operator()
}
GMRES ..> KrylovPrecond

class KrylovPrecond {
    constructor()
    sctl::Long Size()
    sctl::Long Rank() 
    void Append()
    void Apply()
}

class StokesBIO {
    - ker_FxU
    - ker_DxU
    - comm
    - SL_scal_
    - DL_scal_
    - LayerPotenSL
    - LayerPotenDL

    constructor()
    destructor()
    void SetAccuracy()
    void AddElemList()
    void SetPeriodicity()
    void SetTargetCoord()
    void SetTargetNormal()
    long Dim()
    void Setup()
    void ClearSetup()

    void ComputePotential()
}

StokesBIO --> BoundaryIntegralOp

class Annular {
    - Xc_inner
    - Xc_outer
    - r_inner
    - r_outer
    - X_inner 
    - X_outer
    - Xn_inner
    - Xn_outer 
    - min_radius

    constructor() 
    destructor()

    SetInnerXc()
    SetOuterXc()
    SetInnerR()
    SetOuterR()
    SetupInner() 
    SetupOuter() 
    GetInnerCoord()
    GetOuterCoord()
    GetNoteCoord()
    GetCenterLine()
    GetAspectRatio()
}

Annular --> SlenderBodyElem


@enduml